import React, { useState, useMemo } from 'react';
import {
  ScanSearch, Search, Copy, Check, Download,
  ExternalLink, ChevronDown, ChevronUp, Zap,
  AlertTriangle, AlertCircle, Info,
} from 'lucide-react';
import { RECON_CATEGORIES, RISK_META, RISK } from '../data/reconTemplates';

function buildDorks(domain) {
  return RECON_CATEGORIES.map(cat => ({
    ...cat,
    templates: cat.templates.map(t => ({
      ...t,
      query: t.dork.replaceAll('{domain}', domain.trim()),
    })),
  }));
}

const RISK_ICON = {
  critical: <AlertCircle size={11} />,
  high:     <AlertTriangle size={11} />,
  medium:   <Info size={11} />,
};

const RISK_ORDER = { critical: 0, high: 1, medium: 2 };

function RiskBadge({ risk }) {
  const m = RISK_META[risk];
  return (
    <span className={`inline-flex items-center gap-1 text-xs font-medium px-1.5 py-0.5 rounded border ${m.color} ${m.bg} ${m.border}`}>
      {RISK_ICON[risk]}
      {m.label}
    </span>
  );
}

const DOMAIN_RE = /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$/;

function validateDomain(value) {
  const trimmed = value.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
  if (!trimmed) return { valid: false, error: 'Enter a domain name.' };
  if (!DOMAIN_RE.test(trimmed)) return { valid: false, error: 'Enter a valid domain (e.g., example.com).' };
  return { valid: true, domain: trimmed };
}

export default function ReconAnalyzer({ onLoadIntoBuilder, engine, engineUrl }) {
  const [domain, setDomain]         = useState('');
  const [domainError, setDomainError] = useState('');
  const [submitted, setSubmitted]   = useState('');
  const [openCats, setOpenCats]       = useState({});
  const [copiedIdx, setCopiedIdx]     = useState(null);
  const [filterRisk, setFilterRisk]   = useState('all');
  const [runAllDone, setRunAllDone]   = useState(false);

  const results = useMemo(() => submitted ? buildDorks(submitted) : [], [submitted]);

  const allQueries = useMemo(() =>
    results.flatMap(cat => cat.templates.map(t => t.query)),
    [results]
  );

  const filteredResults = useMemo(() =>
    results.map(cat => ({
      ...cat,
      templates: filterRisk === 'all'
        ? cat.templates
        : cat.templates.filter(t => t.risk === filterRisk),
    })).filter(cat => cat.templates.length > 0),
    [results, filterRisk]
  );

  const totalCount   = allQueries.length;
  const criticalCount = results.flatMap(c => c.templates).filter(t => t.risk === RISK.CRITICAL).length;

  const handleSubmit = e => {
    e.preventDefault();
    const { valid, domain: cleanDomain, error } = validateDomain(domain);
    if (!valid) { setDomainError(error); return; }
    setDomainError('');
    setSubmitted(cleanDomain);
    setDomain(cleanDomain);
    // open all categories by default
    const open = {};
    RECON_CATEGORIES.forEach(c => { open[c.id] = true; });
    setOpenCats(open);
    setFilterRisk('all');
    setRunAllDone(false);
  };

  const toggleCat = id => setOpenCats(p => ({ ...p, [id]: !p[id] }));

  const handleCopy = (text, idx) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedIdx(idx);
      setTimeout(() => setCopiedIdx(null), 1200);
    }).catch(() => {});
  };

  const handleSearch = q => {
    window.open(`${engineUrl}${encodeURIComponent(q)}`, '_blank');
  };

  const handleRunAll = () => {
    // browsers block mass window.open — open first 10 to avoid popup blockers
    const toOpen = allQueries.slice(0, 10);
    toOpen.forEach(q => window.open(`${engineUrl}${encodeURIComponent(q)}`, '_blank'));
    setRunAllDone(true);
    setTimeout(() => setRunAllDone(false), 2000);
  };

  const handleExport = () => {
    const lines = [];
    lines.push(`# Recon Dorks — ${submitted}`);
    lines.push(`# Generated by Dorkbase`);
    lines.push(`# Engine: ${engine}`);
    lines.push(`# Date: ${new Date().toISOString().split('T')[0]}`);
    lines.push('');
    results.forEach(cat => {
      lines.push(`## ${cat.label}`);
      cat.templates.forEach(t => {
        lines.push(`# [${RISK_META[t.risk].label}] ${t.label}`);
        lines.push(t.query);
        lines.push('');
      });
    });
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `recon-${submitted}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyAll = () => {
    navigator.clipboard.writeText(allQueries.join('\n')).catch(() => {});
  };

  return (
    <div className="space-y-4">
      {/* Domain input */}
      <div>
        <p className="text-xs text-text-muted mb-3">
          Enter a target domain to generate a full recon dork set, categorized by attack surface with risk ratings.
        </p>
        <form onSubmit={handleSubmit} className="flex gap-2">
          <div className="flex-1 space-y-1">
            <input
              type="text"
              value={domain}
              onChange={e => { setDomain(e.target.value); setDomainError(''); }}
              placeholder="target domain (e.g., example.com)"
              className={`input-field w-full${domainError ? ' border-danger focus:border-danger focus:ring-danger/30' : ''}`}
              autoComplete="off"
              spellCheck={false}
            />
            {domainError && <p className="text-xs text-danger">{domainError}</p>}
          </div>
          <button type="submit" className="btn-primary shrink-0 self-start">
            <ScanSearch size={14} />
            Analyze
          </button>
        </form>
      </div>

      {/* Results */}
      {filteredResults.length > 0 && (
        <>
          {/* Summary bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 py-2 border-y border-border-subtle">
            <div className="flex items-center gap-3 text-xs">
              <span className="text-text-muted">
                <span className="text-text-primary font-semibold">{totalCount}</span> dorks for
                <span className="text-accent-light font-mono ml-1">{submitted}</span>
              </span>
              {criticalCount > 0 && (
                <span className="inline-flex items-center gap-1 text-red-400">
                  <AlertCircle size={11} />
                  {criticalCount} critical
                </span>
              )}
            </div>

            {/* Bulk actions */}
            <div className="flex items-center gap-2">
              <button type="button" onClick={handleCopyAll}
                className="btn-ghost py-1 px-2.5 text-xs">
                <Copy size={11} /> Copy All
              </button>
              <button type="button" onClick={handleRunAll}
                className="btn-ghost py-1 px-2.5 text-xs">
                {runAllDone
                  ? <><Check size={11} className="text-success" /> Opened</>
                  : <><ExternalLink size={11} /> Run All (10)</>
                }
              </button>
              <button type="button" onClick={handleExport}
                className="btn-ghost py-1 px-2.5 text-xs">
                <Download size={11} /> Export .txt
              </button>
            </div>
          </div>

          {/* Risk filter */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs text-text-dim">Filter:</span>
            {['all', RISK.CRITICAL, RISK.HIGH, RISK.MEDIUM].map(r => (
              <button
                key={r}
                type="button"
                onClick={() => setFilterRisk(r)}
                className={`text-xs px-2.5 py-1 rounded-full border transition-colors font-medium
                  ${filterRisk === r
                    ? r === 'all'
                      ? 'border-accent bg-accent/10 text-accent-light'
                      : `${RISK_META[r].border} ${RISK_META[r].bg} ${RISK_META[r].color}`
                    : 'border-border-subtle text-text-dim hover:text-text-muted hover:border-border-active'
                  }`}
              >
                {r === 'all' ? 'All' : RISK_META[r].label}
              </button>
            ))}
          </div>

          {/* Category sections */}
          <div className="space-y-2">
            {filteredResults.map(cat => {
              const isOpen = openCats[cat.id] !== false;
              const catCritical = cat.templates.filter(t => t.risk === RISK.CRITICAL).length;
              return (
                <div key={cat.id} className="border border-border-subtle rounded-md overflow-hidden">
                  {/* Category header */}
                  <button
                    type="button"
                    onClick={() => toggleCat(cat.id)}
                    className="w-full flex items-center justify-between px-3 py-2.5 bg-bg-elevated hover:bg-bg-card transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-semibold text-text-primary uppercase tracking-wider">
                        {cat.label}
                      </span>
                      {catCritical > 0 && (
                        <span className="text-xs text-red-400 flex items-center gap-0.5">
                          <AlertCircle size={10} /> {catCritical}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-text-dim">{cat.templates.length}</span>
                      {isOpen ? <ChevronUp size={13} className="text-text-dim" /> : <ChevronDown size={13} className="text-text-dim" />}
                    </div>
                  </button>

                  {/* Dork rows */}
                  {isOpen && (
                    <div className="divide-y divide-border-subtle">
                      {cat.templates
                        .slice()
                        .sort((a, b) => RISK_ORDER[a.risk] - RISK_ORDER[b.risk])
                        .map((t, i) => {
                          const uid = `${cat.id}-${i}`;
                          return (
                            <div key={i}
                              className="flex items-start gap-3 px-3 py-2.5 bg-bg-secondary hover:bg-bg-elevated transition-colors group">
                              <div className="flex-1 min-w-0 space-y-1">
                                <div className="flex items-center gap-2 flex-wrap">
                                  <RiskBadge risk={t.risk} />
                                  <span className="text-xs font-medium text-text-primary">{t.label}</span>
                                </div>
                                <p className="font-mono text-xs text-accent-light break-all select-all leading-relaxed">
                                  {t.query}
                                </p>
                              </div>
                              {/* Row actions — always visible */}
                              <div className="flex items-center gap-1 shrink-0 pt-0.5">
                                <button type="button"
                                  onClick={() => handleSearch(t.query)}
                                  className="p-1.5 rounded text-text-muted hover:text-accent-light hover:bg-accent/10 transition-colors"
                                  title="Search">
                                  <Search size={12} />
                                </button>
                                <button type="button"
                                  onClick={() => handleCopy(t.query, uid)}
                                  className="p-1.5 rounded text-text-muted hover:text-accent-light hover:bg-accent/10 transition-colors"
                                  title="Copy">
                                  {copiedIdx === uid ? <Check size={12} className="text-success" /> : <Copy size={12} />}
                                </button>
                                <button type="button"
                                  onClick={() => onLoadIntoBuilder(t.query)}
                                  className="p-1.5 rounded text-text-muted hover:text-accent-light hover:bg-accent/10 transition-colors"
                                  title="Load into builder">
                                  <Zap size={12} />
                                </button>
                              </div>
                            </div>
                          );
                        })}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
